src/objects/Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>Log_DateTime__c</fullName>
        <label>Log Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Log_Details__c</fullName>
        <label>Log Details</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Process_Name__c</fullName>
        <label>Process Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>LOG - {000000}</displayFormat>
        <label>Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TransactionLogHandler.cls
public class TransactionLogHandler {
    public static void doHandlerException(System.Exception ex, String processName){
        //TransactionLogHandler.doHandlerException();
        Error_Log__c errLog = new Error_Log__c();
        errLog.Log_Details__c = ex.getStackTraceString() + ' message is : '+ ex.getMessage() + ' Cause : ' +
            ex.getCause() + ' TypeName : ' + ex.getTypeName() + ' LineNumber : ' + ex.getLineNumber();
        errLog.Log_DateTime__c =  System.now();
        errLog.Process_Name__c = processName;
        
        insert errLog;
    }
    
    public static void doHandleExceptionWithError(String errors, String processName){
        //TransactionLogHandler.doHandlerException();
        Error_Log__c errLog = new Error_Log__c();
        errLog.Log_Details__c = errors;
        errLog.Log_DateTime__c =  System.now();
        errLog.Process_Name__c = processName;
        
        insert errLog;
    }


}